name: Format using ktlint

# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every Thursday at 15:45 UTC.
on:
  push:
    branches:
      - master
      - development
  schedule:
    - cron: "45 15 * * 4"

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    name: Format using ktlint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [16]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Format using prettier
        run: npx prettier . --write

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.ACTIONS_GPG_KEY }}
          passphrase: ${{ secrets.ACTIONS_GPG_PASS }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          commit-message: "[Automated] Format using ktlint"
          title: "[Automated] Format using ktlint"
          body: "This is an automated pull request to format the code using ktlint."
          branch: "@shakebot/ktlint-format/ktlint-format-${{ github.sha }}"
          branch-suffix: timestamp
          delete-branch: true
          author: shakebot[bot] <bot@shakelang.com>
          signoff: false
          labels: automated, style
